#!/bin/sh

message_file=$1
if [ -z "$message_file" ] || [ ! -r "$message_file" ]; then
	printf '%s\n' 'commit message file is required' >&2
	exit 1
fi

message=$(sed '/^# ------------------------ >8/,$d; /^[[:space:]]*#/d' "$message_file") || exit 1

if printf '%s\n' "$message" | grep -iE 'co-authored-by|generated with|generated by ai|🤖' >/dev/null; then
	printf '%s\n' 'no AI attribution in commits' >&2
	exit 1
fi

subject=$(printf '%s\n' "$message" | sed -n '1p')
case "$subject" in
Merge\ * | Revert\ * | fixup!* | squash!*) exit 0 ;;
esac

subject_length=$(printf '%s\n' "$subject" | awk '{ print length }')
if [ "$subject_length" -gt 72 ]; then
	printf '%s\n' 'commit subject must be 72 characters or fewer' >&2
	exit 1
fi

case "$subject" in
*.)
	printf '%s\n' 'commit subject must not end in a period' >&2
	exit 1
	;;
esac

if ! printf '%s\n' "$subject" | grep -Eq '^(feat|fix|refactor|perf|docs|test|build|ci|chore|revert)\((hook|mod|readers|e2e|ci|docs|repo|deps)\)!?: [a-z].+$'; then
	printf '%s\n' 'commit subject must use Conventional Commits with an allowed type and scope' >&2
	exit 1
fi

exit 0
